using LittleFeed.Application.Newsletters;
using LittleFeed.Common.Results;
using LittleFeed.Domain;
using LittleFeed.Domain.Newsletters;
using LittleFeed.Dto.Newsletters;
using LittleFeed.Dto.Reader;
using Microsoft.EntityFrameworkCore;

namespace LittleFeed.Services;

public class NewsletterService(ApplicationDbContext dbContext,
    ILogger<NewsletterService> logger) : INewsletterQueries, INewsletterCommands, INewsletterAccess
{
    public Task<List<ListNewsletterDto>> GetNewsletters()
    {
        logger.LogInformation("Listing newsletters");
        return dbContext.Newsletters
            .Select(n => new ListNewsletterDto(
                n.Name,
                n.Slug,
                n.Description,
                n.CreatedAt,
                dbContext.UserProfiles
                    .Where(up => up.UserId == n.OwnerId)
                    .Select(up => new UserIdentificationDto(up.DisplayName, up.Slug))
                    .First()))
            .ToListAsync();
    }

    public Task<List<ListNewsletterDto>> GetNewslettersByUserId(string userId)
    {
        throw new NotImplementedException();
    }

    public Task<List<ListOwnedNewsletterDto>> GetNewslettersUserCanEdit(string userId)
    {
        return dbContext.Newsletters
            .Where(n => n.OwnerId == userId || n.Members.Any(m => m.UserId == userId))
            .Select(n => new ListOwnedNewsletterDto(
                n.Id,
                n.Name,
                n.Slug,
                n.Description,
                n.CreatedAt,
                n.OwnerId == userId
            ))
            .ToListAsync();
    }

    public Task<string?> GetNewsletterSlugIfUserCanEdit(Guid newsletterId, string userId)
    {
        return  dbContext.Newsletters
            .Where(n => n.OwnerId == userId || n.Members.Any(m => m.UserId == userId))
            .Select(n => n.Slug)
            .FirstOrDefaultAsync();
    }

    public async Task<NewsletterDto?> GetNewsletterBySlug(string slug)
    {
        var newsletter = await dbContext.Newsletters
            .Where(n => n.Slug == slug)
            .FirstOrDefaultAsync();
        
        if(newsletter is null)
            return null;

        var ownerProfile = await dbContext.UserProfiles
            .Where(up => up.UserId == newsletter.OwnerId)
            .Select(up => new UserIdentificationDto(up.DisplayName, up.Slug))
            .FirstAsync();

        return new NewsletterDto
        {
            Id = newsletter.Id,
            Name = newsletter.Name,
            Description = newsletter.Description,
            Slug = newsletter.Slug,
            CreatedAt = newsletter.CreatedAt,
            Author = ownerProfile,
        };
    }

    public Task<string?> GetNewsletterSlug(Guid id)
    {
        return dbContext.Newsletters
            .AsNoTracking()
            .Where(n => n.Id == id)
            .Select(n => n.Slug)
            .FirstOrDefaultAsync();
    }

    public Task<bool> ExistsBySlug(string slug)
    {
        return dbContext.Newsletters.AnyAsync(n => n.Slug == slug);
    }

    public Task<bool> CanUserEditNewsletter(Guid id, string userId)
    {
        return dbContext.Newsletters
            .AsNoTracking()
            .AnyAsync(n  => n.Id == id && (n.OwnerId == userId || n.Members.Any(m => m.UserId == userId)));
    }

    public async Task<Result<NewsletterIdentificationDto>> CreateNewsletter(CreateNewsletterDto createDto, string ownerUserId)
    {
        logger.LogInformation("Creating new newsletter");
        
        var newsletter = Newsletter.Create(createDto.Name.Trim(), createDto.Description.Trim(), ownerUserId);
        var isSlugAlreadyUsed = await ExistsBySlug(newsletter.Slug);
        if(isSlugAlreadyUsed)
            return Result<NewsletterIdentificationDto>.Failure("A Newsletter with that name already exists");
        
        await using var transaction = await dbContext.Database.BeginTransactionAsync();
        
        dbContext.Newsletters.Add(newsletter);
        // Id is generated by the database, so SaveChanges is needed before creating dependent rows.
        await dbContext.SaveChangesAsync();
        
        var memberRole = NewsletterMember.CreateOwner(newsletter.Id, ownerUserId);
        dbContext.NewsletterMembers.Add(memberRole);
        var amountSaved = await dbContext.SaveChangesAsync();
        
        await transaction.CommitAsync();
        
        if(amountSaved == 0)
            return Result<NewsletterIdentificationDto>.Failure("Failed to create Newsletter");

        return Result<NewsletterIdentificationDto>.Success(new NewsletterIdentificationDto(newsletter.Name, newsletter.Slug));
    }

    public Task<Newsletter> UpdateNewsletter(Newsletter newsletter)
    {
        throw new NotImplementedException();
    }

    public Task DeleteNewsletter(string id)
    {
        throw new NotImplementedException();
    }
}