using LittleFeed.Domain;
using LittleFeed.Domain.Newsletters;
using LittleFeed.Dto.Newsletters;
using Microsoft.EntityFrameworkCore;

namespace LittleFeed.Services;


public interface INewsletterService
{
    Task<List<ListNewsletterDto>> GetNewsletters();
    Task<Newsletter?> GetNewsletterById(Guid id);
    Task<NewsletterDto?> GetNewsletterBySlug(string slug);
    Task<NewsletterDto> CreateNewsletter(CreateNewsletterDto createDto, string ownerUserId);
    Task<Newsletter> UpdateNewsletter(Newsletter newsletter);
    Task DeleteNewsletter(string id);
}

public class NewsletterService(ApplicationDbContext dbContext,
    ILogger<NewsletterService> logger) : INewsletterService
{
    public Task<List<ListNewsletterDto>> GetNewsletters()
    {
        logger.LogInformation("Listing newsletters");
        return dbContext.Newsletters
            .Select(n => new ListNewsletterDto(n.Name, n.Slug, n.Description, n.CreatedAt))
            .ToListAsync();
    }
    
    public Task<Newsletter?> GetNewsletterById(Guid id)
    {
        return dbContext.Newsletters
            .Where(n => n.Id == id)
            .FirstOrDefaultAsync();
    }

    public async Task<NewsletterDto?> GetNewsletterBySlug(string slug)
    {
        var newsletter = await dbContext.Newsletters
            .Where(n => n.Slug == slug)
            .FirstOrDefaultAsync();
        
        if(newsletter is null)
            return null;

        return new NewsletterDto
        {
            Id = newsletter.Id,
            Name = newsletter.Name,
            Description = newsletter.Description,
            Slug = newsletter.Slug,
            CreatedAt = newsletter.CreatedAt,
        };
    }

    public async Task<NewsletterDto> CreateNewsletter(CreateNewsletterDto createDto, string ownerUserId)
    {
        logger.LogInformation("Creating new newsletter");
        
        await using var transaction = await dbContext.Database.BeginTransactionAsync();
        
        var newsletter = Newsletter.Create(createDto.Name, createDto.Description);
        dbContext.Newsletters.Add(newsletter);
        // Id is generated by the database, so SaveChanges is needed before creating dependent rows.
        await dbContext.SaveChangesAsync();
        
        var memberRole = NewsletterMember.CreateOwner(newsletter.Id, ownerUserId);
        dbContext.NewsletterMembers.Add(memberRole);
        await dbContext.SaveChangesAsync();
        
        await transaction.CommitAsync();
        
        return new NewsletterDto
        {
            Id = newsletter.Id,
            Name = newsletter.Name,
            Description = newsletter.Description,
            Slug = newsletter.Slug,
            CreatedAt = newsletter.CreatedAt,
        };
    }

    public Task<Newsletter> UpdateNewsletter(Newsletter newsletter)
    {
        throw new NotImplementedException();
    }

    public Task DeleteNewsletter(string id)
    {
        throw new NotImplementedException();
    }
}